[Add] Implementation of written in Python
k5342/circuit-calculator pull request #3
Opened 2019-04-25 12:01 UTC by shinkwhek

I wrote it because there was a demand for implementation in python.

2019-04-25 12:11 UTC, shinkwhek commented
Is it better to marge CableBehavior class into Cable class?

2019-04-25 12:41 UTC, k5342 requested changes
Thanks for sending PR. I wish some modify to merge this.

2019-04-25 12:41 UTC, k5342 commented on python/main.py
> +    def __init__(self, c):
I think it is preferable for defining a default value as `[]`. And the variable name `c` makes a little bit confused.

2019-04-25 12:41 UTC, k5342 commented on python/main.py
> +class SerialCable(Cable):
I want `Cable#append` method to modify an existing cable after definition.

2019-04-25 12:41 UTC, k5342 commented on python/main.py
> +class ParalleCable(Cable):
typo: Parallel

2019-04-25 12:41 UTC, k5342 commented on python/main.py
> +# !/path/to/bin/of/python
It seems unnecessary for Python script. It's not a shell script.

2019-04-25 12:41 UTC, k5342 commented on python/main.py
> +        pass
Use `raise NotImplementedError` is preferable on an abstract class rather than `pass`.

2019-04-25 13:31 UTC, shinkwhek commented
修正しました

2019-04-26 04:31 UTC, merged

2019-04-26 04:31 UTC, k5342 commented
LGTM! ありがとうございます！

2019-04-26 05:04 UTC, k5342 commented
Revert しました #8 すみません．こちらひとつのコミットに squash して再度 PR 投げてもらえますか？

2019-04-26 08:45 UTC, shinkwhek commented
了解